# This is a basic workflow to help you get started with Actions

name: Scrape

# Controls when the workflow will run
on:
  schedule:
    - cron: "10 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scrape:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pipenv'
    - run: pipenv install requests bs4 pandas --python `which python`
    - name: Run scraper
      run: python dhb_case.py
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest data"